import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    icon: @image-url("../assets/app-icon.png");
    title: "Oriv";
    preferred-width: 1200px;
    preferred-height: 800px;
    min-width: 800px;
    min-height: 600px;

    in-out property <int> counter: 42;
    callback request-increase-value();
    VerticalBox {



        Rectangle { /* @lsp:ignore-node */ }
    }
}